version: "3.9"

services:
  db:
    image: postgres:15
    container_name: cmpr_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: compressor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
